name: Test

on:
  workflow_dispatch:

jobs:
  exemplo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Comando de teste
        run: echo "Executado manualmente com sucesso!"
